LIB_SOURCES =                       \
c_api/AutoTune_c.cpp       			\
c_api/clone_index_c.cpp            	\
c_api/Clustering_c.cpp            	\
c_api/error_impl.cpp	          	\
c_api/Index_c.cpp	            	\
c_api/index_factory_c.cpp         	\
c_api/index_io_c.cpp            	\
c_api/IndexBinary_c.cpp            	\
c_api/IndexFlat_c.cpp            	\
c_api/IndexIVF_c.cpp            	\
c_api/IndexIVFFlat_c.cpp          	\
c_api/IndexLSH_c.cpp	          	\
c_api/IndexIVFFlat_c.cpp          	\
c_api/IndexPreTransform_c.cpp      	\
c_api/IndexReplicas_c.cpp          	\
c_api/IndexScalarQuantizer_c.cpp   	\
c_api/IndexShards_c.cpp			   	\
c_api/MetaIndexes_c.cpp			   	\
c_api/VectorTransform_c.cpp		   	\
c_api/impl/AuxIndexStructures_c.cpp	\
c_api/utils/distances_c.cpp			\
faiss/AutoTune.cpp    				\
faiss/Clustering.cpp    			\
faiss/IVFlib.cpp    				\
faiss/Index.cpp    					\
faiss/Index2Layer.cpp    			\
faiss/IndexAdditiveQuantizer.cpp    \
faiss/IndexAdditiveQuantizerFastScan.cpp \
faiss/IndexBinary.cpp    			\
faiss/IndexBinaryFlat.cpp    		\
faiss/IndexBinaryFromFloat.cpp    	\
faiss/IndexBinaryHNSW.cpp    		\
faiss/IndexBinaryHash.cpp    		\
faiss/IndexBinaryIVF.cpp    		\
faiss/IndexFastScan.cpp    			\
faiss/IndexFlat.cpp    				\
faiss/IndexFlatCodes.cpp   			\
faiss/IndexHNSW.cpp    				\
faiss/IndexIDMap.cpp    			\
faiss/IndexIVF.cpp    				\
faiss/IndexIVFAdditiveQuantizer.cpp \
faiss/IndexIVFAdditiveQuantizerFastScan.cpp    \
faiss/IndexIVFFastScan.cpp    		\
faiss/IndexIVFFlat.cpp    			\
faiss/IndexIVFPQ.cpp   				\
faiss/IndexIVFPQFastScan.cpp    	\
faiss/IndexIVFPQR.cpp    			\
faiss/IndexIVFSpectralHash.cpp    	\
faiss/IndexLSH.cpp    				\
faiss/IndexLattice.cpp    			\
faiss/IndexNNDescent.cpp    		\
faiss/IndexNSG.cpp    				\
faiss/IndexPQ.cpp    				\
faiss/IndexPQFastScan.cpp    		\
faiss/IndexPreTransform.cpp   		\
faiss/IndexRefine.cpp    			\
faiss/IndexReplicas.cpp    			\
faiss/IndexRowwiseMinMax.cpp    	\
faiss/IndexScalarQuantizer.cpp   	\
faiss/IndexShards.cpp    			\
faiss/IndexShardsIVF.cpp    		\
faiss/MatrixStats.cpp    			\
faiss/MetaIndexes.cpp    			\
faiss/VectorTransform.cpp   		\
faiss/clone_index.cpp    			\
faiss/gpu/GpuAutoTune.cpp   	 	\
faiss/gpu/GpuCloner.cpp    			\
faiss/gpu/GpuResources.cpp    		\
faiss/gpu/StandardGpuResources.cpp  \
faiss/gpu/impl/InterleavedCodes.cpp \
faiss/gpu/impl/RemapIndices.cpp    	\
faiss/gpu/perf/PerfClustering.cpp   \
faiss/gpu/perf/PerfIVFPQAdd.cpp    	\
faiss/gpu/perf/WriteIndex.cpp    	\
faiss/gpu/test/TestCodePacking.cpp  \
faiss/gpu/test/TestGpuIndexBinaryFlat.cpp    \
faiss/gpu/test/TestGpuIndexFlat.cpp  \
faiss/gpu/test/TestGpuIndexIVFFlat.cpp \
faiss/gpu/test/TestGpuIndexIVFPQ.cpp    \
faiss/gpu/test/TestGpuIndexIVFScalarQuantizer.cpp    \
faiss/gpu/test/TestGpuMemoryException.cpp    \
faiss/gpu/test/TestUtils.cpp    		\
faiss/gpu/test/demo_ivfpq_indexing_gpu.cpp \
faiss/gpu/utils/StackDeviceMemory.cpp    \
faiss/gpu/utils/Timer.cpp    			\
faiss/impl/AdditiveQuantizer.cpp    	\
faiss/impl/AuxIndexStructures.cpp    	\
faiss/impl/CodePacker.cpp    			\
faiss/impl/FaissException.cpp    		\
faiss/impl/HNSW.cpp    					\
faiss/impl/IDSelector.cpp    			\
faiss/impl/LocalSearchQuantizer.cpp     \
faiss/impl/NNDescent.cpp    			\
faiss/impl/NSG.cpp    					\
faiss/impl/PolysemousTraining.cpp    	\
faiss/impl/ProductAdditiveQuantizer.cpp \
faiss/impl/ProductQuantizer.cpp    		\
faiss/impl/ResidualQuantizer.cpp    	\
faiss/impl/ScalarQuantizer.cpp    		\
faiss/impl/index_read.cpp    			\
faiss/impl/index_write.cpp    			\
faiss/impl/io.cpp    					\
faiss/impl/kmeans1d.cpp    				\
faiss/impl/lattice_Zn.cpp    			\
faiss/impl/pq4_fast_scan.cpp    		\
faiss/impl/pq4_fast_scan_search_1.cpp   \
faiss/impl/pq4_fast_scan_search_qbs.cpp \
faiss/index_factory.cpp    				\
faiss/invlists/BlockInvertedLists.cpp   \
faiss/invlists/DirectMap.cpp    		\
faiss/invlists/InvertedLists.cpp    	\
faiss/invlists/InvertedListsIOHook.cpp  \
faiss/invlists/OnDiskInvertedLists.cpp  \
faiss/python/python_callbacks.cpp    	\
faiss/utils/Heap.cpp    				\
faiss/utils/WorkerThread.cpp    		\
faiss/utils/distances.cpp    			\
faiss/utils/distances_fused/avx512.cpp  \
faiss/utils/distances_fused/distances_fused.cpp    \
faiss/utils/distances_fused/simdlib_based.cpp    	\
faiss/utils/distances_simd.cpp    		\
faiss/utils/extra_distances.cpp    		\
faiss/utils/hamming.cpp    				\
faiss/utils/partitioning.cpp    		\
faiss/utils/quantize_lut.cpp    		\
faiss/utils/random.cpp    				\
faiss/utils/sorting.cpp    				\
faiss/utils/utils.cpp    				\


sources:
	@for source_file in $(LIB_SOURCES); do \
		echo internal/$$source_file; \
	done